// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXI0OI17Sd-xuHLoMyBMPYF4sGmJl4_zg',
    appId: '1:132507239290:web:07a5286d630a8c11044cc3',
    messagingSenderId: '132507239290',
    projectId: 'todo-task-kausthub',
    authDomain: 'todo-task-kausthub.firebaseapp.com',
    storageBucket: 'todo-task-kausthub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZdNPa3zswpc93IJsKpHf5bDpkZR1MHU',
    appId: '1:132507239290:android:cd415375ed9a4a69044cc3',
    messagingSenderId: '132507239290',
    projectId: 'todo-task-kausthub',
    storageBucket: 'todo-task-kausthub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSdNyttNX7kzFGrKIpA-QpBpidw0zqqI',
    appId: '1:132507239290:ios:85f234c54f0e6f8f044cc3',
    messagingSenderId: '132507239290',
    projectId: 'todo-task-kausthub',
    storageBucket: 'todo-task-kausthub.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSdNyttNX7kzFGrKIpA-QpBpidw0zqqI',
    appId: '1:132507239290:ios:85f234c54f0e6f8f044cc3',
    messagingSenderId: '132507239290',
    projectId: 'todo-task-kausthub',
    storageBucket: 'todo-task-kausthub.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXI0OI17Sd-xuHLoMyBMPYF4sGmJl4_zg',
    appId: '1:132507239290:web:7b90280fed03d0ab044cc3',
    messagingSenderId: '132507239290',
    projectId: 'todo-task-kausthub',
    authDomain: 'todo-task-kausthub.firebaseapp.com',
    storageBucket: 'todo-task-kausthub.firebasestorage.app',
  );
}
